Feature branch 1 (#114)
* removed conflicts

* changes

* adding testing scenario

* code changes

* code changes

* changes to the code

* adding the small changes like sns topic working fixed it

* changes to the webapp

* pushing the csv code

* commit users

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -138,3 +138,25 @@ jobs:
           echo $launchTemplateId
           aws autoscaling update-auto-scaling-group --auto-scaling-group-name "${{ secrets.AWS_AUTO_SCALING_GROUP }}" --launch-template LaunchTemplateId=$launchTemplateId,Version='$Latest'
           echo "Updated autoscaling with the ec2 Launch Template"
+
+          
+      - name: Instance Refresh of the asg with the latest Template
+        run: |
+          aws autoscaling start-instance-refresh --auto-scaling-group-name "${{ secrets.AWS_AUTO_SCALING_GROUP }}"
+          echo "Instance refresh is complete with the latest template and in progress"
+          instance_refresh_flag=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name "${{ secrets.AWS_AUTO_SCALING_GROUP }}" --query "InstanceRefreshes[0].Status" --output text)
+          while true; do
+          if [ "$instance_refresh_flag" = "Successful" ]; then
+          echo "Instance refresh Successful."
+          exit 0
+          elif  [ "$instance_refresh_flag" = "Cancelled" ]; then
+          echo "Instance refresh Cancelled."
+          exit 1
+          elif  [ "$instance_refresh_flag" = "Failed" ]; then
+          echo "Instance refresh failed."
+          exit 1
+          else
+          echo "sleeping and then check again"
+          sleep 10
+          fi
+          done
