Feature branch (#49)
* commenting the yaml files

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* testing the build

* git pushing the app.sh file

* commiting the app.sh script

* commiting the app.sh script

* commiting the app.sh script

* minor changes

* commiting the app.sh script

* commiting the app.sh script

* commiting the app.sh script

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

* making the variables

diff --git a/.github/workflows/validate_pull_request.yml b/.github/workflows/validate_pull_request.yml
--- a/.github/workflows/validate_pull_request.yml
+++ b/.github/workflows/validate_pull_request.yml
@@ -62,7 +62,15 @@ jobs:
           npm test
                 
       - name: Run Packer Build
-        run: packer fmt ./packer/aws-debian.pkr.hcl
+        run: |
+          packer fmt -check ./packer/aws-debian.pkr.hcl
+          if [[ $? -eq 0 ]]; then
+            echo "no formatting required"
+          else
+            echo "formatted and hence exit 1"
+            exit 1
+          fi
+        continue-on-error: false
 
       - name: Run Packer Validate
         run: |
