making the variables

diff --git a/.github/workflows/validate_pull_request.yml b/.github/workflows/validate_pull_request.yml
--- a/.github/workflows/validate_pull_request.yml
+++ b/.github/workflows/validate_pull_request.yml
@@ -64,7 +64,12 @@ jobs:
       - name: Run Packer Build
         run: |
           packer fmt ./packer/aws-debian.pkr.hcl
-          git diff --exit-code
+          if [[ $? -eq 0 ]]; then
+            echo "Packer template formatting and validation succeeded."
+          else
+            echo "Packer template formatting or validation failed."
+            exit 1
+          fi
         continue-on-error: false
 
       - name: Run Packer Validate
